services:
  api:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    restart: unless-stopped

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tmdb
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
